env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust version ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Run tests
        run: |
          set -e
          for backend in ${{ matrix.backends }}; do
            echo "======= NATIVE TESTS $backend ======";
            WGPU_BACKEND=$backend cargo llvm-cov --no-cfg-coverage nextest --no-fail-fast --no-report
          done
        env:
          OPENLIBRARY_ACCESS: ${{ secrets.OPENLIBRARY_ACCESS }}
          OPENLIBRARY_SECRET: ${{ secrets.OPENLIBRARY_SECRET }}
        shell: bash

      - name: Generate coverage report
        run: |
          set -e
          cargo llvm-cov report --lcov --output-path lcov.info
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta, nightly]

name: Rust
on: [push, pull_request]
